### PR TITLE
Pulling in options {}

### PR DESCRIPTION
**Pull request by realadeel**

### CODE REVIEW

**Comment by nlsrchtr** [comment]
Thanks for merging! I still hadn't figured out one problem: I would like to post binary data with the `create_pin` method with the `image` parameter, described in the [documentation](https://developers.pinterest.com/docs/api/pins/). I think there need to be some changes in the Faraday connection to handle binary data. Do you have any idea or experience with it? Would be great to push the image directly.

**Comment by nlsrchtr** [comment]
And yes, I also broke the test suite with `spec_helper.rb:2:in `require': cannot load such file -- pinterest (LoadError)` - maybe you also have a clue on how to fix it.

**Comment by realadeel** [comment]
@nlsrchtr the latest version loads pinterest-api in spec_helper - try that. There was an error before where it was trying to load 'pinterest'

On sending images, I missed it in the first version but we'd just need to use the multipart middleware. Something like this:
http://stackoverflow.com/questions/12146407/post-image-with-faraday-as-parameter

**Comment by nlsrchtr** [comment]
Well, without the following:
```
connection.request :multipart
connection.request :url_encoded
connection.adapter :net_http
```
I get `You need to upload an image or provide the 'image_url' parameter`. But with it, I get `Parameter 'board' is required.` but I'm passing in a board_id. And also setting the adapter fixed to `net_http` doesn't seem to be a good fit - because Faraday is offering to change it. Maybe you find a better way.

And it would be great if we wouldn't need to hand in `image: Faraday::UploadIO.new('path/to/image.jpg', 'image/jpeg')`, but only `image: 'path/to/image.jpg'` and the gem would take care of the rest.

**Pull request merged**
